# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5cb479febf91723f1ed62f1540b719518299283424398b203ee4608b901fb5919a47f1f4f72fd4866c7fb5d19b5f782d21786330b89d7a37817015130871b5d4

test:
  secret_key_base: 19da5bc335b80eb1a2e63c6af42f82e501044de36ab55c103183f466724d8f75e4b8d4ffcad4929f9165f79a1c42f2643c9c93d4749f2be0f54d9bf969a79a30

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
